### ISSUE TITLE
useAllPosts is inefficient with large amount of content

### ISSUE THREAD

**Issue by mirasusanna** [evermade/wp-block-toolkit#5]
Using `useAllPosts` function can be extremely slow in case the site has a lot (thousands, in my case) of posts. It can take dozens of seconds to load everything.

**Comment by tnke** [comment]
If there's thousands of posts, it might be good to look for alternative to `PostControl`. I haven't looked too much into the efficiency of `useSelect`, but it could be that trying to use thousands of posts is always going to be quite slow.

Some ideas that come to mind:

### Require a search input

- Instead of a Combobox, just show a search field, and make debounced searches after 3 or so letters
- I'm not sure if `useSelect` supports search arg, but the API endpoints do, so this could at least work with `apiFetch`
- Selected id information could just be pulled with a standalone `useSelect` so it's not dependent on the fetched list of posts

### Some kind of `usePagedPosts`

- Helper hook that gets posts page by page and exposes a "load next page" -function
- Maintains a "data" array and appends new items to the end when a new page is loaded
- Could be used by all kinds of UI controls, i.e. a dropdown that when you scroll to the end, triggers the load next page function
- Not sure how nice of a user experience that is though, if you have a lot of stuff to go through, maybe searching is better
